import 'package:flutter/material.dart';
import 'dart:async';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
    Widget build(BuildContext context) {
        return MaterialApp(
              title: 'V789c',
                    debugShowCheckedModeBanner: false,
                          home: SplashPage(),
                              );
                                }
                                }

                                class SplashPage extends StatelessWidget {
                                  @override
                                    Widget build(BuildContext context) {
                                        Timer(Duration(seconds: 2), () {
                                              Navigator.pushReplacement(
                                                      context,
                                                              MaterialPageRoute(builder: (context) => StartPage()),
                                                                    );
                                                                        });

                                                                            return Scaffold(
                                                                                  body: Container(
                                                                                          decoration: BoxDecoration(
                                                                                                    image: DecorationImage(
                                                                                                                image: AssetImage("assets/images/wall1.png"),
                                                                                                                            fit: BoxFit.cover,
                                                                                                                                      ),
                                                                                                                                              ),
                                                                                                                                                    ),
                                                                                                                                                        );
                                                                                                                                                          }
                                                                                                                                                          }

                                                                                                                                                          class StartPage extends StatelessWidget {
                                                                                                                                                            @override
                                                                                                                                                              Widget build(BuildContext context) {
                                                                                                                                                                  return Scaffold(
                                                                                                                                                                        body: Stack(
                                                                                                                                                                                children: [
                                                                                                                                                                                          Positioned.fill(
                                                                                                                                                                                                      child: Image.asset(
                                                                                                                                                                                                                    "assets/images/wall2.png",
                                                                                                                                                                                                                                  fit: BoxFit.cover,
                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                  Center(
                                                                                                                                                                                                                                                                              child: ElevatedButton(
                                                                                                                                                                                                                                                                                            child: Text('START'),
                                                                                                                                                                                                                                                                                                          style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                                                                          backgroundColor: Colors.black87,
                                                                                                                                                                                                                                                                                                                                          foregroundColor: Colors.white,
                                                                                                                                                                                                                                                                                                                                                          padding: EdgeInsets.symmetric(horizontal: 40, vertical: 20),
                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                      onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                      Navigator.push(
                                                                                                                                                                                                                                                                                                                                                                                                                        context,
                                                                                                                                                                                                                                                                                                                                                                                                                                          MaterialPageRoute(builder: (context) => WebViewPage()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  class WebViewPage extends StatelessWidget {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: WebView(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        initialUrl: 'https://victoria789.club',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                javascriptMode: JavascriptMode.unrestricted,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }