name: Flutter CI

on:
  push:
    branches:
      - main # หรือ master ถ้าคุณใช้ branch master
  pull_request:
    branches:
      - main # หรือ master ถ้าคุณใช้ branch master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x.x' # คุณสามารถระบุเวอร์ชัน Flutter ที่ต้องการได้ เช่น '3.19.x' หรือ '3.22.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests (optional)
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android APK (optional)
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          
